version: '3'

services:
  testnet:
    image: "ethereum/client-go:alpine"
    volumes:
      - ../eth/:/root/
    ports:
      - "8545:8545"
      - "30303:30303"
    tty: true
    command: --syncmode "fast" --testnet --cache=1024
