version: '3'

services:
  # testrpc:       
  #   ports:
  #     - "8545:8545"
  devnet:
    build:
      context: ..
      dockerfile: vm/Dockerfile.ganache
    entrypoint: ganache-cli
    command: -b 10
  devbox:
    build:
      context: ..
      dockerfile: vm/Dockerfile.devbox
    ports:
      - "8080:8080"
    volumes:
      - ../src/:/src/
      - /src/node_modules
    tty: true
    depends_on: 
      - "devnet"
    environment:
      - RPCPORT=8545
  api:
    build:
      context: ..
      dockerfile: vm/Dockerfile.api
    ports:
      - "3000:3000"
    volumes:
      - ../src/:/src/
      - /src/node_modules
    tty: true
    depends_on:     
      - "devbox"
    environment:
      - HOST=0.0.0.0
      - RPCHOST=testrpc
      - RPCPORT=8545

