version: '3'

services:
    testbox:
        build:
            context: ..
            dockerfile: vm/Dockerfile.testbox
        volumes:
            - ../src/:/src/
            - /src/node_modules
            - /src/build
        depends_on:
            - "testrpc"
